name: Hexo Deploy

on:
  push:
    branches:
      - main  # 或 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate & Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          hexo clean
          hexo generate
          hexo deploy